### ISSUE TITLE
Berkeley Migration

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1331]
This is a meta issue to track tasks for successful migration to Berkeley schema

Tasks:

- [ ] Investigate removing the `used` column from some workflow tables (#1484)
- [ ] ~~Investigate the use of the progress bar during metagenome annotation ingest~~
- [ ] Clean up references to `omics_processing`, including changing table name (#1485)
- [ ] Update column name for `relevant_protocols` on study model (#1483)
- [x] Update user-facing language (e.g. omics processing -> data generation) (#1326) 
- [x] Update ingest code (#1295)
- [x] Update dependencies to use berkeley packages (#1374, #1368) <- note that this should be revisited as newer versions get released
- [x] Front-end changes for submission schema updates (#1375) 

### Context
Meta-issue tracking progress of ensuring `nmdc-server` code is compatible with the ["Berkeley" schema](https://github.com/microbiomedata/berkeley-schema-fy24) for NMDC.  The `berkeley-schema-migration` [branch](https://github.com/microbiomedata/nmdc-server/tree/berkeley-schema-migration) is meant to hold all changes related to the migration.

**Comment by ssarrafan** [comment]
Moving this to the next sprint. Meta issue.

**Comment by mslarae13** [comment]
Meta-issue, going to set the due date to just before full freeze for final testing. Date TBC

**Comment by mslarae13** [comment]
2 unchecked tasks don't have to be part of the MVP

**Comment by ssarrafan** [comment]
Moving to next sprint
If the plan is to hold off on the two remaining tasks for a while please let me know so I can remove from sprint 
@naglepuff @mslarae13

**Comment by mslarae13** [comment]
Goot question @ssarrafan !

@naglepuff do you plan to work on this issue this sprint or between now and the roll out?
Or will the last 2 things happen post roll out?

**Comment by mslarae13** [comment]
Will not work on the 2 unchecked items this sprint. Moving to Backlog

**Comment by mslarae13** [comment]
@naglepuff 
Will the uncheck items be completed? Can we close this issue?

**Comment by naglepuff** [comment]
I will open new issues for the unchecked items so we can close this.

**Comment by naglepuff** [comment]
Unchecked items have either been removed or spun out into separate issues.
